export const DASHBOARD_SECTIONS = [
  { description: "Observation trends across Costa Rica.", id: "national-trends", label: "National trends" },
  { description: "Observations from OSA Conservation projects.", id: "osa-stats", label: "OSA stats" },
];

export const DASHBOARD_REPORT_CATEGORIES = [
  { id: "observation-stats", label: "Observation stats", sectionId: "osa-stats" },
  { id: "observer-stats", label: "Observer stats", sectionId: "osa-stats" },
];

export const OSA_STATS_REPORTS = [
  { categoryId: "observer-stats", fileName: "abs-vs-obs-active-observers.csv", id: "active-observers", infoText: "An active observer has uploaded at least one observation during the 365 days before this report was generated. The lifespan values are the active observers' average time between first and last observed dates.", label: "Active observers", sectionId: "osa-stats", visualization: { annotationColumn: "observer_percentage", ariaLabel: "Active and inactive observers in ABS, OBS, and aggregated observations", categoryColumn: "activity_status", categoryLabels: { active: "Active observers", inactive: "Inactive observers" }, seriesColumn: "project_alias", seriesLabels: { abs: "ABS", aggregated: "Aggregated", obs: "OBS" }, seriesOrder: ["abs", "obs", "aggregated"], seriesSummaryLabel: "active observers average lifespan", seriesSummaryValueLabel: "days", totalColumn: "average_active_observer_lifespan_days", type: "grouped-bar", valueColumn: "observer_count", valueLabel: "observers" } },
  { categoryId: "observation-stats", fileName: "abs-vs-obs-observations-by-day.csv", id: "observations-by-day", label: "Observations per day", sectionId: "osa-stats", visualization: { ariaLabel: "Time series comparing ABS, OBS, and aggregated observations", dateColumn: "observed_date", seriesColumn: "project_alias", seriesLabels: { abs: "ABS", aggregated: "Aggregated", obs: "OBS" }, seriesOrder: ["abs", "obs", "aggregated"], type: "time-series", valueColumn: "observation_count", valueLabel: "observations" } },
  { categoryId: "observation-stats", fileName: "abs-vs-obs-observation-counts.csv", id: "observation-counts", label: "Observations per project", relatedDownloads: [{ fileName: "abs-vs-obs-duplicate-observations.csv", id: "duplicate-observations", label: "Download duplicate observations CSV" }], sectionId: "osa-stats", visualization: { ariaLabel: "Pie chart of observations per project", categoryColumn: "project_alias", categoryLabels: { abs: "ABS", obs: "OBS" }, excludedCategories: ["aggregated"], summaryItems: [{ label: "Duplicate observations", sourceId: "duplicate-observations", valueColumn: "duplicate_observation_count", valueLabel: "observations" }], totalCategory: "aggregated", totalLabel: "Total observations", type: "pie", valueColumn: "observation_count", valueLabel: "observations" } },
  { categoryId: "observation-stats", fileName: "abs-vs-obs-quality-grades.csv", id: "quality-grades", label: "Quality grades", sectionId: "osa-stats", visualization: { annotationColumn: "project_observation_percentage", ariaLabel: "Grouped bar chart comparing ABS, OBS, and aggregated observations by quality grade", categoryColumn: "quality_grade", categoryLabels: { casual: "Casual", needs_id: "Needs ID", research: "Research grade" }, hiddenTotalSeries: ["aggregated"], seriesColumn: "project_alias", seriesLabels: { abs: "ABS", aggregated: "Aggregated", obs: "OBS" }, seriesOrder: ["abs", "obs", "aggregated"], totalColumn: "project_total_observation_count", totalLabel: "Total observations", totalObservationColumn: "total_observation_count", totalSeriesId: "aggregated", type: "grouped-bar", valueColumn: "observation_count", valueLabel: "observations" } },
  { categoryId: "observer-stats", fileName: "abs-vs-obs-observers-by-month.csv", id: "observers-over-time", label: "Observers over time", sectionId: "osa-stats", visualization: { allowedGroupings: ["month", "year"], ariaLabel: "Observers joining ABS, OBS, and aggregated observations over time", dateColumn: "period_start", defaultGrouping: "month", defaultRangePreset: "last-90", measures: [{ id: "new", label: "New observers", valueColumn: "new_observer_count", valueLabel: "observers" }, { id: "cumulative", label: "Cumulative total", valueAggregation: "latest", valueColumn: "cumulative_observer_count", valueLabel: "observers" }], seriesColumn: "project_alias", seriesLabels: { abs: "ABS", aggregated: "Aggregated", obs: "OBS" }, seriesOrder: ["abs", "obs", "aggregated"], type: "time-series", valueColumn: "new_observer_count", valueLabel: "observers" } },
];

export const OSA_STATS_DATA_FILES = [
  ...OSA_STATS_REPORTS.map(({ fileName, id, label }) => ({ fileName, id, label })),
  ...OSA_STATS_REPORTS.flatMap((report) => report.relatedDownloads ?? []),
];
