INSERT INTO observations (
    project_alias,
    download_date,
    observation_id,
    quality_grade,
    species_guess,
    observed_on,
    observed_at,
    created_at,
    updated_at,
    longitude,
    latitude,
    location,
    place_guess,
    positional_accuracy,
    public_positional_accuracy,
    geoprivacy,
    taxon_geoprivacy,
    obscured,
    mappable,
    captive,
    project_ids,
    project_ids_with_curator_id,
    project_ids_without_curator_id,
    identifications_count,
    num_identification_agreements,
    num_identification_disagreements,
    taxon_id,
    observer_id,
    loaded_from,
    loaded_at
)
VALUES (
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, now()
)
ON CONFLICT (project_alias, observation_id) DO UPDATE SET
    download_date = EXCLUDED.download_date,
    quality_grade = EXCLUDED.quality_grade,
    species_guess = EXCLUDED.species_guess,
    observed_on = EXCLUDED.observed_on,
    observed_at = EXCLUDED.observed_at,
    created_at = EXCLUDED.created_at,
    updated_at = EXCLUDED.updated_at,
    longitude = EXCLUDED.longitude,
    latitude = EXCLUDED.latitude,
    location = EXCLUDED.location,
    place_guess = EXCLUDED.place_guess,
    positional_accuracy = EXCLUDED.positional_accuracy,
    public_positional_accuracy = EXCLUDED.public_positional_accuracy,
    geoprivacy = EXCLUDED.geoprivacy,
    taxon_geoprivacy = EXCLUDED.taxon_geoprivacy,
    obscured = EXCLUDED.obscured,
    mappable = EXCLUDED.mappable,
    captive = EXCLUDED.captive,
    project_ids = EXCLUDED.project_ids,
    project_ids_with_curator_id = EXCLUDED.project_ids_with_curator_id,
    project_ids_without_curator_id = EXCLUDED.project_ids_without_curator_id,
    identifications_count = EXCLUDED.identifications_count,
    num_identification_agreements = EXCLUDED.num_identification_agreements,
    num_identification_disagreements = EXCLUDED.num_identification_disagreements,
    taxon_id = EXCLUDED.taxon_id,
    observer_id = EXCLUDED.observer_id,
    loaded_from = EXCLUDED.loaded_from,
    loaded_at = now();
